### ISSUE TITLE
Example in readme isn't working

### ISSUE THREAD

**Issue by alexkwolfe** [jimeh/redistat#10]
I decided to give Redistat a shot today.  Unfortunately, I couldn't make it past the example in the readme.  I'm on Redis 2.0.4.

```
  ruby-1.9.2-p136 :015 > class VisitorStats
  ruby-1.9.2-p136 :016?>     include Redistat::Model
  ruby-1.9.2-p136 :017?>   end
   => VisitorStats 
  ruby-1.9.2-p136 :018 > VisitorStats.store('/about', {:views => 1})
   => #<Redistat::Event:0x00000101a14008 @raw_options={}, @options={:depth=>:hour, :store_event=>false, :connection_ref=>nil, :enable_grouping=>true, :label_indexing=>true}, @key=VisitorStats//about:2011031511, @stats={:views=>1}, @meta={}, @new=false> 
  ruby-1.9.2-p136 :019 > stats = VisitorStats.fetch('/about', 2.hour.ago, Time.now)
   => [{}] 
  ruby-1.9.2-p136 :020 > stats.total
   => {}
```

**Comment by alexkwolfe** [comment]
Oops.  Almost forgot the Redistat version:
    $ gem list | grep redistat
    redistat (0.2.4)

**Comment by jimeh** [comment]
Try storing and fetching `about` instead of `/about`.

I've unfortunately not had time to update the readme to reflect the new grouping features introduced in 0.2.x.

As a short example, if you store something with a label of `views/about` and another store with `views/contact`, fetching each of those will work as expected, but fetching the `views` label will contain the summary of both.

I'll be updating the readme asap. Just been in a hurry to meet a couple of deadlines the last few days. I'll be pushing pre-release gems in the future when docs and implementation don't match.

**Comment by alexkwolfe** [comment]
After changing the key, it seems there might still be a problem.  The fetch appears to be looking too "far ahead":

The code:
    require 'redistat'
    class VisitorStats
      include Redistat::Model
    end
    VisitorStats.store('about', {:views => 1})
    VisitorStats.fetch('about', 1.hour.ago, Time.now)
    => [{}]

What happens in Redis:
    +1300216163.992028 "hincrby" "VisitorStats/about:2011" "views" "1"
    +1300216163.992334 "hincrby" "VisitorStats/about:201103" "views" "1"
    +1300216163.992591 "hincrby" "VisitorStats/about:20110315" "views" "1"
    +1300216163.992843 "hincrby" "VisitorStats/about:2011031514" "views" "1"
    +1300216163.993119 "sadd" "VisitorStats.label_index:" "about"
    +1300216164.701462 "hgetall" "VisitorStats/about:2011031513"

It appears as though the fetch method isn't looking in the right key.  Shouldn't it be doing `hgetall VisitorStats/about:2011031514`?

**Comment by jimeh** [comment]
Yes, you're right. That's my mistake in the readme. Technically it's working at it should, it's simply that the depth is set to :hour, and thanks to the way it intelligently tries to select as few keys as possible, it does not include the current unit of the end time.

Potentially it should actually be picking both hours when it's the bottom depth. However, that also get's confusing, cause if you're storing stats to a depth of an hour and the current time is `14:25`, then `1.hour.ago` means you want to include the previous hour, but `Time.now` is a fair bit into hour 14, so should that be selected too effectively returning 2 full hours of stats? In my original reasoning, no. It shouldn't.

It's been a good 6-7 months since I messed with the date range selection code, but I will be going over again soon just for sanity's sake.

Right now I'm working on an updated readme, with *actually* working examples, and some more details.

**Comment by jimeh** [comment]
As of v0.2.5 a decent readme with fully working examples is included.
